image: python:3.10

stages:
  - test
  - publish

test:
  stage: test
  before_script:
    - python -m pip install --upgrade pip
    - python -m pip install -e .[test]
  script:
    - python -m pytest tests/
  only:
    - pushes
    - merge_requests

pypi:
  stage: publish
  before_script:
    - python -m pip install --upgrade pip
    - pip install build twine
  script:
    - python -m build
    - TWINE_PASSWORD=$PYPI_API_TOKEN TWINE_USERNAME=__token__ python -m twine upload dist/*
  only:
    - tags
